Sm 21 mantenedor de mesas
ariaka-cl/SmartGourmet pull request #6
Opened 2019-02-26 20:17 UTC by IgnacioRojasJorquera

En este mantenedor de mesas permite gestionar las mesas del restaurant ya sea para agregar, modificar o eliminar una mesa con sus atributos como numero de mesa, capacidad de la mesa y el estado que se encuentra aquella mesa

2019-02-28 01:19 UTC, jtabilot requested changes

2019-02-28 01:19 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/ProductosAPIController.vb
> +                'Dim cate As Categoria = New Categoria
Eliminar Comentario

2019-02-28 01:19 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/ProductosAPIController.vb
> +                    'cate = db.Categorias.Where(Function(c) c.ID = id).SingleOrDefault
Eliminar codigo comentado

2019-02-28 19:18 UTC, IgnacioRojasJorquera commented on ARIAKA.SmartGourmet.WEB/Controllers/API/ProductosAPIController.vb
> +                'Dim cate As Categoria = New Categoria
borrado

2019-02-28 19:18 UTC, IgnacioRojasJorquera commented on ARIAKA.SmartGourmet.WEB/Controllers/API/ProductosAPIController.vb
> +                    'cate = db.Categorias.Where(Function(c) c.ID = id).SingleOrDefault
borrado

2019-03-01 02:35 UTC, jtabilot requested changes

2019-03-01 02:35 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Scripts/app/Mesas/mesas.ts
> +                    //+ " <b>ID:</b>" + itemData.ID + "<br>"
eliminar comentario

2019-03-01 08:28 UTC, IgnacioRojasJorquera commented on ARIAKA.SmartGourmet.WEB/Scripts/app/Mesas/mesas.ts
> +                    //+ " <b>ID:</b>" + itemData.ID + "<br>"
Se ha eliminado el comentario

2019-03-01 15:32 UTC, jtabilot approved these changes

2019-03-01 15:32 UTC, merged