SM-22-Creacion_Pedidos
ariaka-cl/SmartGourmet pull request #8
Opened 2019-03-17 00:43 UTC by FranciscoCHT

Se implementa la creación de pedidos, mediante un formulario que acepta pedidos a domicilio, también permite agregar productos(separados por categoría) a una lista, permite la creación de clientes sin requerir otras vistas. 
Se rehace la vista de mesas, para que trabaje de acorde a la creación de pedidos.

2019-03-19 02:48 UTC, jtabilot requested changes

2019-03-19 02:48 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                listPedido = db.Pedidos.Where(Function(p) p.Mesa.ID = id And (p.EstadoPedido = 0 Or p.EstadoPedido = 1)).ToList()
Cambiar por el enum ya que si pones 0 o 1 no ayuda en la legibilidad del código. 
Deberias poner `p.EstadoPedido = EstadoPedido.Preparacion Or p.EstadoPedido = EstadoPedido.Listo`

2019-03-19 02:48 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                'Dim listUsuarios As List(Of Usuario) = db.Usuarios.ToList()
Eliminar comentarios

2019-03-19 02:48 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                    'Dim user As Usuario = listUsuarios.Where(Function(u) u.ID = Producto.Tipo_ID).SingleOrDefault
Sino se utiliza eliminar

2019-03-19 02:48 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                'If db.Pedidos.Where(Function(p) p.Nombre = model.Nombre).Any Then
codigo comentado no se debe versionar

2019-03-19 02:48 UTC, jtabilot commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                'Dim listProductos As List(Of ProductoResultSet) = db.GetProdSinFoto.ToList()
si no se utiliza eliminar

2019-03-19 05:51 UTC, FranciscoCHT commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                listPedido = db.Pedidos.Where(Function(p) p.Mesa.ID = id And (p.EstadoPedido = 0 Or p.EstadoPedido = 1)).ToList()
Modificado.

2019-03-19 05:51 UTC, FranciscoCHT commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                'Dim listUsuarios As List(Of Usuario) = db.Usuarios.ToList()
Eliminado.

2019-03-19 05:51 UTC, FranciscoCHT commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                    'Dim user As Usuario = listUsuarios.Where(Function(u) u.ID = Producto.Tipo_ID).SingleOrDefault
Eliminado.

2019-03-19 05:51 UTC, FranciscoCHT commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                'If db.Pedidos.Where(Function(p) p.Nombre = model.Nombre).Any Then
Eliminado.

2019-03-19 05:53 UTC, FranciscoCHT commented on ARIAKA.SmartGourmet.WEB/Controllers/API/PedidosAPIController.vb
> +                'Dim listProductos As List(Of ProductoResultSet) = db.GetProdSinFoto.ToList()
Estos comentarios los estaba utilizando como base para modificar el problema conversado de la demora, de todas maneras lo dejé como estaba y los comentarios ya han sido eliminados.

2019-03-23 00:45 UTC, jtabilot approved these changes

2019-03-23 00:45 UTC, merged